name: advent
version: 0.1.0.0
synopsis: My solutions for the puzzles during the advent of code.
license: BSD3
author: Patrick Herrmann
copyright: 2016 Patrick Herrmann
maintainer: patrickwherrmann@gmail.com
category: Puzzles

github: patrickherrmann/advent

ghc-options:
  -O2
  -Wall
  -fno-warn-incomplete-patterns
  -fno-warn-unused-do-bind
default-extensions:
  - LambdaCase
  - ViewPatterns
dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - aeson
    - array
    - base16-bytestring
    - bytestring
    - containers
    - cryptohash
    - lens
    - mtl
    - parsec
    - safe
    - scientific
    - split
    - text

benchmarks:
  criterion:
    source-dirs: bench
    main: Benchmarks.hs
    default-extensions: QuasiQuotes
    dependencies:
      - advent
      - criterion
      - heredoc
