flags: {}
extra-deps:
- aeson-0.10.0.0
- attoparsec-0.13.0.1
- base16-bytestring-0.1.1.6
- byteable-0.1.1
- cryptohash-0.11.6
- dlist-0.7.1.2
- hashable-1.2.3.3
- mtl-2.2.1
- parsec-3.1.9
- primitive-0.6.1.0
- safe-0.3.9
- scientific-0.3.4.4
- split-0.2.2
- syb-0.6
- text-1.2.2.0
- unordered-containers-0.2.5.1
- vector-0.11.0.0
resolver: ghc-7.10.3
