flags: {}
extra-deps:
- Glob-0.7.5
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-0.10.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- attoparsec-0.13.0.1
- base16-bytestring-0.1.1.6
- blaze-builder-0.4.0.1
- byteable-0.1.1
- cassava-0.4.4.0
- cereal-0.5.1.0
- criterion-1.1.0.0
- cryptohash-0.11.6
- dlist-0.7.1.2
- erf-2.0.0.0
- hashable-1.2.3.3
- hastache-0.6.1
- ieee754-0.7.8
- math-functions-0.1.5.2
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.3.2
- optparse-applicative-0.12.0.0
- parallel-3.2.1.0
- parsec-3.1.9
- primitive-0.6.1.0
- random-1.1
- safe-0.3.9
- scientific-0.3.4.4
- split-0.2.2
- statistics-0.13.2.3
- syb-0.6
- text-1.2.2.0
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.1.0
- vector-th-unbox-0.2.1.3
resolver: ghc-7.10.3
