flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.0.0
- MissingH-1.3.0.1
- hslogger-1.2.9
- mtl-2.2.1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- split-0.2.2
- text-1.2.1.3
resolver: ghc-7.10.3
